image: maven:3.6.3

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn clean install
      - step:
          name: Deploy to Heroku
          script:
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: "prtappsteve"
                HEROKU_APP_DIR: 'target'
                ZIP_FILE: 'target/' # Update this with the path to your jar
