#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: zip file
          script:
            - apt-get update
            - apt-get -y install zip
            - zip -r application.zip .
      - step:
          name: Deploy to Heroku
          deployment: production
          script:
            - pipe: atlassian/heroku-deploy:2.4.0
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: 'prtappsteve'
                ZIP_FILE: "application.zip"
